integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: debug_gauntlet_v0.3 # v0.4.0
  # git_commit: # OR use your commit hash
  pip_install: -e ".[gpu]"
  ssh_clone: false # Should be true if using a private repo

command: |
  pip uninstall mosaicml -y
  pip install git+https://github.com/bmosaicml/composer.git@error_logging_callback
  cd llm-foundry/scripts
  composer eval/eval.py /mnt/config/parameters.yaml

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $RUN_NAME
name: gauntlet-v0.2.1
gpu_num: 8
gpu_type: a100_40gb
cluster: r1z2 # replace with your cluster here!

image: mosaicml/llm-foundry:2.1.0_cu121_flash2-latest

# The below is injected as a YAML file: /mnt/config/parameters.yaml
parameters:
  dist_timeout: 6000
  seed: 1
  max_seq_len: 2048
  device_eval_batch_size: 1
  precision: amp_bf16

  models:
  -
    model_name: meta-llama/Llama-2-7b-hf
    # Tokenizer
    tokenizer:
      name: meta-llama/Llama-2-7b-hf
      kwargs:
        model_max_length: ${max_seq_len}

    model:
      name: hf_causal_lm
      pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
      init_device: mixed
      pretrained: true
      use_auth_token: true

  # FSDP config for model sharding
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: FULL
    forward_prefetch: True
    limit_all_gathers: True


  icl_tasks:
  -
    label: human_eval
    dataset_uri: eval/local_data/programming/human_eval.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot: [0]
    pass_at_k: 1
    num_beams: 5
    batch_size: 1
    icl_task_type: code_evaluation
  -
    label: gsm8k
    dataset_uri: eval/local_data/symbolic_problem_solving/gsm8k_prepended_8shot.jsonl
    num_fewshot: [0]
    icl_task_type: question_answering
    cot_delimiter: 'The answer is '
    continuation_delimiter: "\n\nA:"
    question_prelimiter: ""
    do_normalization: false
    early_stopping_criteria:
    - "\n\n"
    - "Question:"
  # eval_gauntlet: 'eval/yamls/eval_gauntlet_v0.3.yaml'

  callbacks:
    eval_output_logging:
      subset_sample: -1
      output_directory: s3://mosaicml-internal-checkpoints-test/test_icl_output_logger_llama2-7b-gauntlet-v0.3
