max_seq_len: 1024
seed: 1
precision: fp32

# If you are using one model, put it here:
model_name_or_path: EleutherAI/gpt-neo-125m
# otherwise, write a block for each model you want to test in the `models` section

models:
-
  model_name: ${model_name_or_path}
  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: ${model_name_or_path}
    init_device: mixed
    pretrained: true
  tokenizer:
    name: ${model_name_or_path}
    kwargs:
      model_max_length: ${max_seq_len}
# # if you are evaluating more than one model, list them all as YAML blocks without variable interpolation
# -
#   model_name: mosaicml/mpt-7b
#   model:
#     name: hf_causal_lm
#     pretrained_model_name_or_path: mosaicml/mpt-7b
#     init_device: cpu
#     pretrained: true
#     config_overrides:
#       max_seq_len: ${max_seq_len}
#   tokenizer:
#     name: mosaicml/mpt-7b
#     kwargs:
#       model_max_length: ${max_seq_len}


device_eval_batch_size: 4

# FSDP config for model sharding
# fsdp_config:
#   sharding_strategy: FULL_SHARD
#   mixed_precision: FULL
#   forward_prefetch: True
#   limit_all_gathers: True

icl_tasks:
-
  label: gsm8k
  dataset_uri: eval/local_data/symbolic_problem_solving/gsm8k_prepended_8shot.jsonl
  num_fewshot: [0]
  icl_task_type: question_answering
  cot_delimiter: 'The answer is '
  continuation_delimiter: "\n\nA:"
  question_prelimiter: ""
  do_normalization: false
  early_stopping_criteria:
  - "\n\n"
  - "Question:"
-
  label: human_eval
  dataset_uri: eval/local_data/programming/human_eval.jsonl # ADD YOUR OWN DATASET URI
  num_fewshot: [0]
  pass_at_k: 1
  num_beams: 5
  batch_size: 1
  icl_task_type: code_evaluation
# eval_gauntlet: 'eval/yamls/eval_gauntlet_v0.3.yaml'

callbacks:
  eval_output_logging:
    subset_sample: -1
    output_directory: s3://mosaicml-internal-checkpoints-test/test_icl_output_logger_llama2-7b-gauntlet-v0.3
